services:
  sso:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/Dockerfile
    container_name: sso-app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=sso-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - REDIS_HOST=sso-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT}
      - REDIS_DB=${REDIS_DB}
      - KAFKA_HOST=sso-kafka
      - KAFKA_PORT=29092
      - KAFKA_TIMEOUT=${KAFKA_TIMEOUT}
      - GRPC_ADDR=:50051
      - GRPC_TIMEOUT=${GRPC_TIMEOUT}
      - LOG_LEVEL=${LOG_LEVEL}
      - JWT_TODOAPP_KEY=${JWT_TODOAPP_KEY}
      - JWT_TTL=${JWT_TTL}
      - SESSION_TTL=${SESSION_TTL}
    ports:
      - 50051:50051
    restart:
      always
  sso-postgres:
    image: postgres:18.3-bookworm
    container_name: sso-postgres-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${PROJECT_ROOT}/out/pg/data:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    restart:
      always

  sso-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
      - ${PROJECT_ROOT}/migrations:/migrations

  sso-redis:
    image: redis:8.8.0
    container_name: sso-redis-db
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT}
      - REDIS_DB=${REDIS_DB}
    entrypoint: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${PROJECT_ROOT}/out/redis/data:/data
    ports:
      - ${REDIS_PORT}:6379
    restart:
      always

  sso-kafka:
    image: apache/kafka:4.3.1
    container_name: sso-broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://sso-kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - ${PROJECT_ROOT}/out/kafka/data:/tmp/kafka-logs
    ports:
      - 9092:9092
    restart:
      always

  sso-kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: sso-broker-ui
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: sso-kafka:29092
  